checks:
    php: true
build:
    environment:
        php:
            version: 5.6.33
    dependencies:
            before:
                - pecl install swoole-1.9.23
                - composer install
    nodes:
            analysis:
                project_setup:
                    override: true
                tests:
                    override: [php-scrutinizer-run]