checks:
    php: true
filter:
    excluded_paths:
      - 'tests/*'
build:
    environment:
        php:
            version: 5.6.33
            ini:
                'date.timezone': 'Asia/Shanghai'
    dependencies:
            before:
                - pecl install swoole-1.9.23
                - composer install
                - composer require laravel/framework:~5.1.0
    nodes:
            analysis:
                project_setup:
                    override: true
                tests:
                    override:
                        - php-scrutinizer-run --enable-security-analysis